id: a101e74c3aad4615b15c3fb953d80140
initial_creation_type: ocr
source_metadata:
  volumes:
    faf0d6acb85044abad00eb007e95d134:
      base_file: v076.txt
      image_group_id: I1PD95922
      title: ''
      total_pages: 1517
      volume_number: 77
